### ISSUE TITLE
Header parsing with empty content in the first line

### ISSUE THREAD

**Issue by murdej** [vaibhavpandeyvpz/phemail#10]
If the email contains a header in this format, 
```
Subject:
 =?iso-8859-2?Q?FW:_KOPIE_dokladu_Stavebniny_DEK_a.s._xxxxxxxxx_-_NEPLA?=
 =?iso-8859-2?Q?=ABTE_ji=BE_hrazeno_v_hotovosti?=
```
the header is ignored. I have prepared a pull request with a fix.

https://github.com/vaibhavpandeyvpz/phemail/pull/9

**Comment by vaibhavpandeyvpz** [comment]
This PR https://github.com/vaibhavpandeyvpz/phemail/pull/9 you mean?

**Comment by vaibhavpandeyvpz** [comment]
Merged as lgtm
