### ISSUE TITLE
Problem with getContents() and Attachments

### ISSUE THREAD

**Issue by DantesGG** [vaibhavpandeyvpz/phemail#11]
Hey there. I have an .eml file and i cannot get the content and attachments of it. It returns undefined-null. I tried your plain text .eml file and is working. but the multipart is not as my own file not working as well. I think the problem is with the html content in it. There is a specific way to get the content of multipart .eml? I m gonna attach my file but it will be on txt since git doesnt support eml.
[file.txt](https://github.com/vaibhavpandeyvpz/phemail/files/13361962/file.txt)

**Comment by gaurav1992chd** [comment]
Hey, I am getting the same problem. The getContents() function returns null value.
Can you please let me know how to resolve it?
Thanks!
